server:
  port: 8000
spring:
  config:
    activate:
      on-profile: stg
  datasource:
    url: jdbc:mysql://localhost:3306/real_estate
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0