server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://root:TuLDJTsQqjagrAPdxwWbkqdUgMOEnSte@interchange.proxy.rlwy.net:37426/railway
    username: root
    password: TuLDJTsQqjagrAPdxwWbkqdUgMOEnSte
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloudinary:
  cloud_name: dn2m3s9k0
  api_key: 378291597432836
  api_secret: 9AuvGB1tA5cF0juYBQ5jqbo3Xwg
